name: Build Docker image and push static file to webhost

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
  
jobs:
  build_arlofail:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      # Check out code
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build image and generate static files
        run: |
          bash buildtools/builder.sh

      - name: Scan image
        id: scan
        uses: sysdiglabs/scan-action@v3
        with:
          image-tag: "arlo.fail:nginx-amd64"
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          input-type: docker-daemon
          run-as-user: root

      - name: Scan image arm
        id: scan-arm
        uses: sysdiglabs/scan-action@v3
        with:
          image-tag: "arlo.fail:nginx-arm64"
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          input-type: docker-daemon
          run-as-user: root

      # Create a release after a successfull build and image scanning
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
  
      - name: Update Scan results
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: ${{ steps.scan.outputs.sarifReport }}

      - name: Push image
        run: |
          docker tag arlo.fail:nginx-amd64 darkvex/fail-builder:arlo.fail-amd64-${{ steps.release.outputs.version }}
          docker tag arlo.fail:nginx-arm64 darkvex/fail-builder:arlo.fail-arm64-${{ steps.release.outputs.version }}
          docker push darkvex/fail-builder:arlo.fail-amd64-${{ steps.release.outputs.version }}
          docker push darkvex/fail-builder:arlo.fail-arm64-${{ steps.release.outputs.version }}

      - name: Push image
        run: |
          docker manifest create \
          darkvex/fail-builder:arlo.fail-${{ steps.release.outputs.version }} \
          --amend darkvex/fail-builder:arlo.fail-amd64-${{ steps.release.outputs.version }} \
          --amend darkvex/fail-builder:arlo.fail-arm64-${{ steps.release.outputs.version }}
          docker manifest push darkvex/fail-builder:arlo.fail-${{ steps.release.outputs.version }}

